languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Amazon ECS Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = "UA-44634850-2"
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon ECS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
editURL = "https://github.com/brentley/ecsworkshop/edit/master/content/"

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @brentContained"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=brentContained"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @realadamjkeller"
identifier = "twa"
url = "https://twitter.com/intent/user?screen_name=realadamjkeller"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AppMesh Workshop"
url = "https://appmeshworkshop.com"
weight = 6

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> EKS Workshop"
url = "https://eksworkshop.com"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard'></i> AWS Partner Workshops"
url = "https://awsworkshop.io"
weight = 8

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
