baseURL = "https://ecsworkshop.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amazon ECS Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = "UA-44634850-2"
sectionPagesMenu = "main"
#pygmentsCodeFences = true
#pygmentsCodeFencesGuessSyntax = true
#pygmentsStyle = "monokai"
relativeURLs = "true"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon ECS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true
disableInlineCopyToClipBoard = true

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @brentContained"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=brentContained"
weight = 1

[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
